name = "discord-clone"
compatibility_date = "2025-04-17"
packageManager = "pnpm"

[build]
  command = "pnpm --filter @workspace/discord-clone run build"

pages_build_output_dir = "./artifacts/discord-clone/dist"
